"""add review findings

Revision ID: 0ebfe18d88f2
Revises: 17c35725a067
Create Date: 2026-09-13 17:35:21.443319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebfe18d88f2'
down_revision: Union[str, Sequence[str], None] = '17c35725a067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_category'), 'review_findings', ['category'], unique=False)
    op.create_index(op.f('ix_review_findings_id'), 'review_findings', ['id'], unique=False)
    op.create_index(op.f('ix_review_findings_review_run_id'), 'review_findings', ['review_run_id'], unique=False)
    op.create_index(op.f('ix_review_findings_severity'), 'review_findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_findings_severity'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_review_run_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_category'), table_name='review_findings')
    op.drop_table('review_findings')
    # ### end Alembic commands ###
