"""create review runs table

Revision ID: 17c35725a067
Revises: e013e491091f
Create Date: 2026-09-06 18:02:47.244238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c35725a067'
down_revision: Union[str, Sequence[str], None] = 'e013e491091f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('pull_request_number', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_runs_id'), 'review_runs', ['id'], unique=False)
    op.create_index(op.f('ix_review_runs_pull_request_number'), 'review_runs', ['pull_request_number'], unique=False)
    op.create_index(op.f('ix_review_runs_repository_id'), 'review_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_review_runs_status'), 'review_runs', ['status'], unique=False)
    op.create_index(op.f('ix_review_runs_tenant_id'), 'review_runs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_runs_tenant_id'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_status'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_repository_id'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_pull_request_number'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_id'), table_name='review_runs')
    op.drop_table('review_runs')
    # ### end Alembic commands ###
