"""add reset password fields

Revision ID: 79d37ddec537
Revises: 129f92b10d78
Create Date: 2026-08-10 00:38:36.079507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d37ddec537'
down_revision: Union[str, Sequence[str], None] = '129f92b10d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_password_expiry', sa.DateTime(timezone=True), nullable=True))
    # keep existing verification_token unique constraint
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_verification_token'), 'users', ['verification_token'])
    op.drop_column('users', 'reset_password_expiry')
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
